from __future__ import annotations
import grpc
import pytest

# Dynamic gRPC imports from generated code
# These will be generated by running grpc_tools.protoc


def _get_product_stub() -> tuple:
    """Create gRPC channel to product service. Returns (stub, channel) or raises skip."""
    try:
        channel = grpc.insecure_channel("127.0.0.1:19090")
        # Try a quick connectivity check
        grpc.channel_ready_future(channel).result(timeout=3)
    except Exception:
        pytest.skip("gRPC server not reachable on 127.0.0.1:19090")
    try:
        from ecommerce import product_pb2_grpc
    except ImportError:
        pytest.skip("gRPC stubs not generated — run grpc_tools.protoc first")
    return product_pb2_grpc.ProductServiceStub(channel), channel


def _get_inventory_stub() -> tuple:
    """Create gRPC channel to inventory service."""
    try:
        channel = grpc.insecure_channel("127.0.0.1:19090")
        grpc.channel_ready_future(channel).result(timeout=3)
    except Exception:
        pytest.skip("gRPC server not reachable")
    try:
        from ecommerce import inventory_pb2_grpc
    except ImportError:
        pytest.skip("gRPC stubs not generated")
    return inventory_pb2_grpc.InventoryServiceStub(channel), channel


def test_grpc_list_products():
    """gRPC ProductService.ListProducts returns products."""
    try:
        stub, channel = _get_product_stub()
        from ecommerce import product_pb2
        req = product_pb2.ListProductsReq(page=1, size=10)
        resp = stub.ListProducts(req)
        assert resp.total >= 0, "Expected total field in response"
    finally:
        if 'channel' in dir():
            channel.close()


def test_grpc_get_stock(product_id):
    """gRPC InventoryService.GetStock returns stock info."""
    if product_id is None:
        pytest.skip("No product_id available")
    try:
        stub, channel = _get_inventory_stub()
        from ecommerce import inventory_pb2
        req = inventory_pb2.GrpcGetStockReq(product_id=product_id)
        resp = stub.GetStock(req)
        assert resp.available >= 0, f"Expected available >= 0, got: {resp.available}"
    finally:
        if 'channel' in dir():
            channel.close()
